FROM php:7.1.19-fpm-alpine3.7

RUN apk add --update --no-cache -t .php-rundeps \
        fcgi \
        findutils \
        "freetype=2.8.1-r3" \
        git \
        "gmp=6.1.2-r1" \
        "icu-libs=59.1-r1" \
        "libjpeg-turbo=1.5.2-r0" \
        "libjpeg-turbo-utils=1.5.2-r0" \
        "libltdl=2.4.6-r4" \
        "libmcrypt=2.5.8-r7" \
        "libpng=1.6.34-r1" \
        "libxslt=1.1.31-r0" \
        make \
        "mariadb-client=10.1.32-r0" \
        nano \
        openssh \
        openssh-client \
        patch \
        rsync \
        su-exec \
        sudo \
        tig \
        tmux \
        "yaml=0.1.7-r0"; \
    \
    apk add --update --no-cache -t .build-deps \
        autoconf \
        cmake \
        build-base \
        bzip2-dev \
        freetype-dev \
        geoip-dev \
        gmp-dev \
        icu-dev \
        jpeg-dev \
        libjpeg-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libtool \
        libxslt-dev \
        pcre-dev \
        yaml-dev; \
    \
    docker-php-ext-install \
        bcmath \
        calendar \
        exif \
        gmp \
        intl \
        mcrypt \
        mysqli \
        opcache \
        pcntl \
        pdo_mysql \
        sockets \
        xmlrpc \
        xsl \
        zip; \
    \
    # GD
    docker-php-ext-configure gd \
        --with-gd \
        --with-freetype-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/; \
    NPROC=$(getconf _NPROCESSORS_ONLN); \
    docker-php-ext-install "-j${NPROC}" gd; \
    \
    pecl install \
        "redis-3.1.6" \
        "yaml-2.0.2"; \
    docker-php-ext-enable \
        redis \
        yaml; \
    \
    # Uploadprogress
    mkdir -p /usr/src/php/ext/uploadprogress; \
    up_url="https://github.com/wodby/pecl-php-uploadprogress/archive/latest.tar.gz"; \
    wget -qO- "${up_url}" | tar xz --strip-components=1 -C /usr/src/php/ext/uploadprogress; \
    docker-php-ext-install uploadprogress; \
    \
    # Install composer
    wget -qO- https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer; \
    \
    # Plugin for parallel install
    composer global require "hirak/prestissimo:^0.3"; \
    \
    rm -rf \
        /usr/src/php/ext/ast \
        /usr/src/php/ext/uploadprogress \
        /usr/include/php \
        /usr/lib/php/build \
        /tmp/* \
        /root/.composer \
        /var/cache/apk/*;

COPY ./html /var/www/html

RUN composer install

