logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedByDefault = false

[acme]
email = "comunicaitalia@agid.gov.it"
storage = "/etc/traefik/conf/acme.json"
entryPoint = "https"
onHostRule = true
[acme.tlsChallenge]
