<?php

use \Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Implements hook_page_attachments_alter().
 *
 * Hides the meta name Generator on the site to avoid showing the current version of Drupal.
 */
function version_hide_page_attachments_alter(array &$attachments) {
  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if ($attachment[1] == 'system_meta_generator') {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
}

/**
 * Implement hook_js_alter().
 *
 * Removes the version of Drupal from the query string of core libraries.
 * 
 * @see \Drupal\Core\Asset\JsCollectionRenderer.php::render()
 */
function version_hide_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  foreach ($javascript as &$item) {
    if (strpos($item['data'], 'core/misc') !== FALSE) {
      $item['version'] = -1;
    }
  }
}
